version: '2'

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "8000:8000"
            - "443:443"
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
#    client:
#        container_name: dev
#        build:
#            context: ./www/frontend
#        ports:
#            - "3000:3000"
#        volumes:
#          - ./www/frontend:/client